add_executable(merge_sort  merge_sort.cpp)
add_executable(remove_element  remove_element.cpp)
add_executable(removeDuplicates  removeDuplicates.cpp)
add_executable(majorityElement  majorityElement.cpp)
add_executable(rotate  rotate.cpp)
add_executable(maxProfit  maxProfit.cpp)
add_executable(canJump  canJump.cpp)
add_executable(hIndex  hIndex.cpp)
add_executable(test  test.cpp)